# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  host: ec2-23-21-164-107.compute-1.amazonaws.com
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  database: d9q34bpi7btis0
  username: pbvqjhpevnbxrb
  password: be895cd17ef4a762ae936ddfa66e687ac4eb01e8e82a440ece70a076c36b4994

test:
  database: d9q34bpi7btis0
  username: pbvqjhpevnbxrb
  password: be895cd17ef4a762ae936ddfa66e687ac4eb01e8e82a440ece70a076c36b4994

production:
  database: d9q34bpi7btis0
  username: pbvqjhpevnbxrb
  password: be895cd17ef4a762ae936ddfa66e687ac4eb01e8e82a440ece70a076c36b4994
